services:
  app:
    image: golang:1.27-alpine
    working_dir: /app/metrics/prometheus
    volumes:
      - ../../:/app
    command: >
      sh -c "
        go mod tidy &&
        go build -o /tmp/pipeline_example ./example/ &&
        /tmp/pipeline_example
      "
    ports:
      - "2112:2112"
    networks:
      - pipeline-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - pipeline-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
    networks:
      - pipeline-net

networks:
  pipeline-net:
    driver: bridge